version: '3.1'

volumes:
  postgres-data:

services:
  postgres:
    image: 'postgres:13'
    restart: 'always'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
