version: '3.1'

volumes:
  postgis-data:

services:
  postgis:
    image: 'postgis/postgis:13-master'
    restart: 'always'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "postgis-data:/var/lib/postgisql/data"
