version: '3.1'

volumes:
  postgis-data:

services:
  postgis:
    image: postgis/postgis:13-master
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgis-data:/var/lib/postgisql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

  map-ui:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./map-ui:/usr/share/nginx/html:ro

  tileserver:
    build: ./tileserver
    ports:
      - 3000:80
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgis
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: mcis
      HTTP_PORT: 80
      HTTP_ADDRESS: 0.0.0.0
    depends_on:
      postgis:
        condition: service_healthy
